//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Request
    {
        public int id { get; set; }

        
        public int project_id { get; set; }
        public int department_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        [DisplayName("Time Request Made")]
        public string time { get; set; }

        [DisplayName("Description of Request")]
        public string description { get; set; }

        [DisplayName("Department Name")]
        public virtual Department Department { get; set; }
        
        [DisplayName("Requested By")]
        public virtual Employee Employee { get; set; }
        
        [DisplayName("Project Name")]
        public virtual Project Project { get; set; }
    }
}
